# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Personajes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Personajes

  target 'PersonajesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PersonajesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Moya', '13.0.0'
end
